# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61c65dd53adc96d9bd8e41f8f8193c7eba9a280f6450ba65dec2b8a244ab0c981058d037ef0488938ca8f4b923a2444f528f44fb0f0067e831c12182954da56f

test:
  secret_key_base: 5a33283bf26417ececc54056972c8a6118ad59690d01dea6665d85321054ba89cc0e85b52d2638be7ae78165318cbc70441166af125ad475aca398657dcf0243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
